name: test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
